import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronRight, AlertCircle, TrendingUp, Download } from 'lucide-react';
import api from '../services/api';
import ToggleSwitch from '../components/ToggleSwitch';
import LoadingSpinner from '../components/LoadingSpinner';
import CircularProgress from '../components/CircularProgress';
import BackgroundBlobs from '../components/BackgroundBlobs';
import { savePCOSResult } from '../services/healthStore';
import { downloadPCOSPDF } from '../services/pdfDownload';

// ── PDF Download ─────────────────────────────────────────────────
function downloadReport(formData, result) {
  const userEmail = localStorage.getItem('userEmail') || 'Patient';
  const date = new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'long', year:'numeric' });
  const riskColor = { Low: '#16a34a', Medium: '#d97706', High: '#dc2626' }[result.riskLevel] || '#7B5CB0';

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<title>BioSense PCOS Report</title>
<style>
  body { font-family: Georgia, serif; background: #F8F4FF; margin: 0; padding: 30px; color: #2D2D2D; }
  .header { background: linear-gradient(135deg,#7B5CB0,#CDB4DB); color: white; padding: 30px; border-radius: 16px; margin-bottom: 24px; }
  .header h1 { margin: 0 0 4px; font-size: 26px; }
  .header p  { margin: 0; opacity: 0.85; font-size: 14px; }
  .card { background: white; border-radius: 12px; padding: 24px; margin-bottom: 18px; box-shadow: 0 2px 12px rgba(123,92,176,0.1); }
  .card h2 { margin: 0 0 16px; color: #7B5CB0; font-size: 18px; border-bottom: 2px solid #E5D9FF; padding-bottom: 8px; }
  .risk-badge { display:inline-block; padding: 12px 30px; border-radius: 50px; font-size: 22px; font-weight: bold; color: white; background: ${riskColor}; margin: 8px 0; }
  .risk-num { font-size: 48px; font-weight: bold; color: ${riskColor}; }
  .factor { margin-bottom: 14px; }
  .factor-label { display: flex; justify-content: space-between; margin-bottom: 4px; font-size: 14px; }
  .bar-bg { background: #E5D9FF; border-radius: 6px; height: 10px; }
  .bar-fill { background: linear-gradient(90deg,#B8A4E3,#7B5CB0); border-radius: 6px; height: 10px; }
  .rec { display: flex; gap: 12px; align-items: flex-start; margin-bottom: 12px; }
  .rec-num { background: #7B5CB0; color: white; border-radius: 50%; width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; font-size: 12px; flex-shrink: 0; margin-top: 2px; }
  .disclaimer { background: #FEF3C7; border: 1px solid #FCD34D; border-radius: 8px; padding: 14px; font-size: 12px; color: #92400E; margin-top: 18px; }
  .footer { text-align: center; color: #9B7FD4; font-size: 12px; margin-top: 20px; }
</style>
</head>
<body>
<div class="header">
  <h1>💜 BioSense — PCOS Risk Assessment Report</h1>
  <p>Patient: ${userEmail} &nbsp;|&nbsp; Date: ${date} &nbsp;|&nbsp; Age: ${formData.age} &nbsp;|&nbsp; Weight: ${formData.weight}kg &nbsp;|&nbsp; Height: ${formData.height}cm</p>
</div>

<div class="card" style="text-align:center">
  <h2>Risk Score</h2>
  <div class="risk-num">${result.risk}%</div><br/>
  <div class="risk-badge">${result.riskLevel} Risk</div>
</div>

<div class="card">
  <h2>Top Influencing Factors</h2>
  ${result.topFactors.map(f => `
    <div class="factor">
      <div class="factor-label"><span>${f.name}</span><span>${f.impact}%</span></div>
      <div class="bar-bg"><div class="bar-fill" style="width:${f.impact}%"></div></div>
    </div>`).join('')}
</div>

<div class="card">
  <h2>Personalised Recommendations</h2>
  ${result.recommendations.map((r, i) => `<div class="rec"><div class="rec-num">${i+1}</div><div style="font-size:14px">${r}</div></div>`).join('')}
</div>

<div class="disclaimer">
  ⚠️ <strong>Medical Disclaimer:</strong> This report is for screening purposes only and does not constitute a medical diagnosis. Please consult a qualified gynaecologist or endocrinologist for professional evaluation and treatment.
</div>
<div class="footer">Generated by BioSense AI Platform &nbsp;|&nbsp; ${date}</div>
</body></html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `BioSense_PCOS_Report_${Date.now()}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

const PCOSPrediction = () => {
  const [formData, setFormData] = useState({
    age: '', weight: '', height: '', periodFrequency: '',
    weightGain: false, hairGrowth: false, skinDarkening: false,
    hairThinning: false, acne: false, fastFood: false,
    exercise: false, moodSwings: false,
    periodRegularity: '', periodDuration: '',
  });
  const [loading, setLoading] = useState(false);
  const [result,  setResult]  = useState(null);
  const [errors,  setErrors]  = useState({});

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    setErrors(prev => ({ ...prev, [name]: '' }));
  };

  const validateForm = () => {
    const newErrors = {};
    if (!formData.age || formData.age < 12 || formData.age > 60) newErrors.age = 'Age must be between 12 and 60';
    if (!formData.weight || formData.weight < 30 || formData.weight > 200) newErrors.weight = 'Weight must be between 30 and 200 kg';
    if (!formData.height || formData.height < 100 || formData.height > 220) newErrors.height = 'Height must be between 100 and 220 cm';
    if (!formData.periodFrequency) newErrors.periodFrequency = 'Period frequency is required';
    if (!formData.periodRegularity) newErrors.periodRegularity = 'Period regularity is required';
    if (!formData.periodDuration) newErrors.periodDuration = 'Period duration is required';
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validateForm()) return;
    setLoading(true);
    try {
      const response = await api.predictPCOS(formData);
      savePCOSResult(formData, response);
      setResult(response);
    } catch (error) {
      console.error('Prediction error:', error);
      alert('Failed to generate prediction. Please ensure the backend is running on port 8000.');
    } finally {
      setLoading(false);
    }
  };

  const getRiskLevelColor = (level) => ({
    Low:    'text-green-600 bg-green-50 border-green-200',
    Medium: 'text-amber-600 bg-amber-50 border-amber-200',
    High:   'text-red-600 bg-red-50 border-red-200',
  }[level] || 'text-amber-600 bg-amber-50 border-amber-200');

  return (
    <div className="min-h-screen pt-24 pb-16 px-6">
      <BackgroundBlobs />
      <div className="container mx-auto max-w-6xl">

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-display font-bold mb-4">
            PCOS Risk <span className="gradient-text">Assessment</span>
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Complete the screening questionnaire to receive your personalised PCOS risk analysis
          </p>
        </motion.div>

        <AnimatePresence mode="wait">
          {!result ? (
            <motion.form key="form" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              onSubmit={handleSubmit} className="glass-card rounded-3xl p-8 shadow-card">

              {/* Basic Information */}
              <div className="mb-8">
                <h2 className="text-2xl font-display font-semibold mb-6 text-gray-800">Basic Information</h2>
                <div className="grid md:grid-cols-3 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Age (years)</label>
                    <input type="number" name="age" value={formData.age} onChange={handleChange} className="input-field" placeholder="e.g., 28" />
                    {errors.age && <p className="text-red-500 text-sm mt-1">{errors.age}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Weight (kg)</label>
                    <input type="number" name="weight" value={formData.weight} onChange={handleChange} className="input-field" placeholder="e.g., 65" />
                    {errors.weight && <p className="text-red-500 text-sm mt-1">{errors.weight}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Height (cm)</label>
                    <input type="number" name="height" value={formData.height} onChange={handleChange} className="input-field" placeholder="e.g., 165" />
                    {errors.height && <p className="text-red-500 text-sm mt-1">{errors.height}</p>}
                  </div>
                </div>
              </div>

              {/* Menstrual History */}
              <div className="mb-8">
                <h2 className="text-2xl font-display font-semibold mb-6 text-gray-800">Menstrual History</h2>
                <div className="grid md:grid-cols-3 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Period Frequency (days)</label>
                    <input type="number" name="periodFrequency" value={formData.periodFrequency} onChange={handleChange} className="input-field" placeholder="e.g., 30" />
                    {errors.periodFrequency && <p className="text-red-500 text-sm mt-1">{errors.periodFrequency}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Period Regularity</label>
                    <select name="periodRegularity" value={formData.periodRegularity} onChange={handleChange} className="input-field">
                      <option value="">Select...</option>
                      <option value="regular">Regular</option>
                      <option value="irregular">Irregular</option>
                    </select>
                    {errors.periodRegularity && <p className="text-red-500 text-sm mt-1">{errors.periodRegularity}</p>}
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Period Duration (days)</label>
                    <input type="number" name="periodDuration" value={formData.periodDuration} onChange={handleChange} className="input-field" placeholder="e.g., 5" />
                    {errors.periodDuration && <p className="text-red-500 text-sm mt-1">{errors.periodDuration}</p>}
                  </div>
                </div>
              </div>

              {/* Symptoms & Lifestyle */}
              <div className="mb-8">
                <h2 className="text-2xl font-display font-semibold mb-6 text-gray-800">Symptoms & Lifestyle</h2>
                <div className="grid md:grid-cols-2 gap-6">
                  <ToggleSwitch label="Recent Weight Gain"      name="weightGain"    checked={formData.weightGain}    onChange={handleChange} />
                  <ToggleSwitch label="Excessive Hair Growth"   name="hairGrowth"    checked={formData.hairGrowth}    onChange={handleChange} />
                  <ToggleSwitch label="Skin Darkening"          name="skinDarkening" checked={formData.skinDarkening} onChange={handleChange} />
                  <ToggleSwitch label="Hair Thinning"           name="hairThinning"  checked={formData.hairThinning}  onChange={handleChange} />
                  <ToggleSwitch label="Acne Problems"           name="acne"          checked={formData.acne}          onChange={handleChange} />
                  <ToggleSwitch label="Frequent Fast Food"      name="fastFood"      checked={formData.fastFood}      onChange={handleChange} />
                  <ToggleSwitch label="Regular Exercise"        name="exercise"      checked={formData.exercise}      onChange={handleChange} />
                  <ToggleSwitch label="Mood Swings"             name="moodSwings"    checked={formData.moodSwings}    onChange={handleChange} />
                </div>
              </div>

              <div className="flex justify-center">
                <button type="submit" disabled={loading}
                  className="btn-primary inline-flex items-center gap-2 text-lg px-8 py-4">
                  {loading ? 'Analyzing...' : 'Get Risk Assessment'}
                  <ChevronRight className="w-5 h-5" />
                </button>
              </div>
            </motion.form>
          ) : (
            <motion.div key="results" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }} className="space-y-6">

              {/* Risk Score */}
              <div className="glass-card rounded-3xl p-8 shadow-card text-center">
                <h2 className="text-2xl font-display font-semibold mb-8 text-gray-800">Your PCOS Risk Assessment</h2>
                <div className="flex justify-center mb-8">
                  <CircularProgress percentage={result.risk} />
                </div>
                <div className={`inline-flex items-center gap-2 px-6 py-3 rounded-full border-2 font-semibold ${getRiskLevelColor(result.riskLevel)}`}>
                  <AlertCircle className="w-5 h-5" />
                  {result.riskLevel} Risk Level
                </div>
              </div>

              {/* Top Factors */}
              <div className="glass-card rounded-3xl p-8 shadow-card">
                <h3 className="text-xl font-display font-semibold mb-6 flex items-center gap-2">
                  <TrendingUp className="w-6 h-6 text-lavender-600" /> Top Influencing Factors
                </h3>
                <div className="space-y-4">
                  {result.topFactors.map((factor, index) => (
                    <motion.div key={index} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * 0.1 }}>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-gray-700 font-medium">{factor.name}</span>
                        <span className="text-lavender-600 font-semibold">{factor.impact}%</span>
                      </div>
                      <div className="w-full bg-lavender-100 rounded-full h-3 overflow-hidden">
                        <motion.div className="h-full bg-gradient-to-r from-lavender-400 to-accent-purple rounded-full"
                          initial={{ width: 0 }} animate={{ width: `${factor.impact}%` }} transition={{ duration: 1, delay: index * 0.1 }} />
                      </div>
                    </motion.div>
                  ))}
                </div>
              </div>

              {/* Recommendations */}
              <div className="glass-card rounded-3xl p-8 shadow-card">
                <h3 className="text-xl font-display font-semibold mb-6 text-gray-800">Personalised Recommendations</h3>
                <div className="space-y-3">
                  {result.recommendations.map((rec, index) => (
                    <motion.div key={index} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: index * 0.1 }} className="flex items-start gap-3 p-4 bg-lavender-50 rounded-xl">
                      <div className="w-6 h-6 rounded-full bg-lavender-500 flex items-center justify-center flex-shrink-0 mt-0.5">
                        <span className="text-white text-sm font-semibold">{index + 1}</span>
                      </div>
                      <p className="text-gray-700 leading-relaxed">{rec}</p>
                    </motion.div>
                  ))}
                </div>
              </div>

              {/* Actions */}
              <div className="flex flex-wrap gap-4 justify-center">
                <button onClick={() => setResult(null)} className="btn-secondary">Take Assessment Again</button>
                <button onClick={() => downloadPCOSPDF({ formData, result, date: new Date().toISOString(), type: 'PCOS Risk Assessment' })}
                  className="btn-primary inline-flex items-center gap-2">
                  <Download className="w-4 h-4" /> Download Report
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {loading && (
          <div className="fixed inset-0 bg-lavender-900/20 backdrop-blur-sm flex items-center justify-center z-50">
            <div className="glass-card rounded-3xl p-12 shadow-glow">
              <LoadingSpinner size="lg" message="Analyzing your health data..." />
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default PCOSPrediction;
